In [1]:
import sys
sys.path.insert(1, '../')
from FrenetFDA.utils.Frenet_Serret_utils import solve_FrenetSerret_ODE_SE, solve_FrenetSerret_ODE_SO
from FrenetFDA.processing_Frenet_path.estimate_Frenet_curvatures import ApproxFrenetODE, LocalApproxFrenetODE
import FrenetFDA.utils.visualization as visu
import numpy as np

INFO: Using numpy backend


In [2]:
N = 200
grid = np.linspace(0,1,N+1)

""" __________ Definition of exact function Theta ___________ """

curv = lambda s : 2*np.cos(2*np.pi*s) + 5
tors = lambda s : 2*np.sin(2*np.pi*s) + 1

def theta(s):
    if isinstance(s, int) or isinstance(s, float):
        return np.array([curv(s), tors(s)])
    elif isinstance(s, np.ndarray):
        return np.vstack((curv(s), tors(s))).T
    else:
        raise ValueError('Variable is not a float, a int or a NumPy array.')

    
Z0 = np.eye(4)
Z = solve_FrenetSerret_ODE_SE(theta, grid, Z0)
Q = Z[:,:3,:3]

###
###
### Approx Frenet ODE

In [3]:
theta_smooth_Bspline = ApproxFrenetODE(grid, Z=Z).Bspline_smooth_estimates(30, order=4, regularization_parameter=0.00001)
theta_smooth_Bspline.plot()

In [4]:
nb_basis_list = np.array([10, 20, 30])
regularization_parameter_list = np.array([0.01, 0.0001, 0.000001])
nb_basis_opt, reg_param_opt, tab_GCV_scores_1 = ApproxFrenetODE(grid, Z=Z).grid_search_optimization_hyperparameters(nb_basis_list, regularization_parameter_list, order=4, parallel=False)

Begin grid search optimisation with 9 combinations of parameters...
Optimal parameters selected by grid search optimisation:  nb_basis = 30 regularization_parameter = 1e-06


In [5]:
nb_basis_list = np.array([[10,10], [20,10], [30,10]])
regularization_parameter_list = np.array([[0.01,0.01], [0.0001, 0.001],[0.0001,0.000001]])
nb_basis_opt, reg_param_opt, tab_GCV_scores_2 = ApproxFrenetODE(grid, Z=Z).grid_search_optimization_hyperparameters(nb_basis_list, regularization_parameter_list, order=4, parallel=False)

Begin grid search optimisation with 9 combinations of parameters...
Optimal parameters selected by grid search optimisation:  nb_basis = [20 10] regularization_parameter = [1.e-04 1.e-06]


In [6]:
print(tab_GCV_scores_1)
print(tab_GCV_scores_2)

[[4.27364936e-02 1.47098832e-04 1.74463950e-05]
 [4.26665187e-02 1.00629295e-04 1.83986440e-05]
 [4.26711322e-02 1.02589970e-04 1.30947958e-05]]
[[4.27364936e-02 5.83985404e-04 1.41787779e-04]
 [4.26841141e-02 5.54948488e-04 9.10137009e-05]
 [4.26849504e-02 5.60515897e-04 9.18734238e-05]]


###
###
### Local Approx Frenet ODE

In [3]:
theta_smooth_Bspline = LocalApproxFrenetODE(grid, Z=Z).Bspline_smooth_estimates(0.01, 30, order=4, regularization_parameter=0.0000001)
theta_smooth_Bspline.plot()

 /home/pchassat/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning:Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.


Opti method 1

In [10]:
# nb_basis_list = np.array([10, 20 ,30])
# regularization_parameter_list = np.array([0.01, 0.0001, 0.000001])
# h_param_list = np.array([0.01, 0.1, 0.2])
nb_basis_list = np.array([20, 25])
regularization_parameter_list = np.array([1e-06, 5e-06])
h_param_list = np.array([0.01, 0.015, 0.02])
h_opt, nb_basis_opt, regularization_parameter_opt, tab_GCV_scores_3, tab_err_h = LocalApproxFrenetODE(grid, Z=Z).grid_search_optimization_hyperparameters(h_param_list, nb_basis_list, regularization_parameter_list, method='1')

Begin grid search optimisation with 12 combinations of parameters...


/home/pchassat/.local/lib/python3.8/site-packages/numpy/core/fromnumeric.py:43: VisibleDeprecationWarning:

Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.



Optimal parameters selected by grid search optimisation:  bandwidth = 0.02 nb_basis = 20 regularization_parameter = 1e-06


In [11]:
print(tab_GCV_scores_3)
print(tab_err_h)

[[[1.04567155e-06 8.93891236e-06]
  [4.62421827e-07 3.47249123e-06]
  [4.34126118e-07 2.87535595e-06]]

 [[1.04852674e-06 8.94048980e-06]
  [4.66305199e-07 3.46954385e-06]
  [4.43684684e-07 2.87178748e-06]]]
[0.00234316 0.00103805 0.0008312 ]


Opti method 3

In [12]:
# nb_basis_list = np.array([10, 20 ,30])
# regularization_parameter_list = np.array([0.01, 0.0001, 0.000001])
# h_param_list = np.array([0.01, 0.1, 0.2])
nb_basis_list = np.array([20, 25])
regularization_parameter_list = np.array([1e-06, 5e-06])
h_param_list = np.array([0.01, 0.015, 0.02])
h_opt, nb_basis_opt, regularization_parameter_opt, tab_GCV_scores_4, tab_err_h_2 = LocalApproxFrenetODE(grid, Z=Z).grid_search_optimization_hyperparameters(h_param_list, nb_basis_list, regularization_parameter_list, method='3')

Begin grid search optimisation with 12 combinations of parameters...
Begin grid search optimisation with 4 combinations of parameters...
Optimal parameters selected by grid search optimisation:  nb_basis = 20 regularization_parameter = 1e-06
Begin grid search optimisation with 4 combinations of parameters...
Optimal parameters selected by grid search optimisation:  nb_basis = 20 regularization_parameter = 1e-06
Begin grid search optimisation with 4 combinations of parameters...
Optimal parameters selected by grid search optimisation:  nb_basis = 20 regularization_parameter = 1e-06
Optimal parameters selected by grid search optimisation:  bandwidth = 0.02 nb_basis = 20.0 regularization_parameter = 1e-06


In [13]:
print(tab_GCV_scores_4)
print(tab_err_h_2)

[[[1.04567155e-06 8.93891236e-06]
  [1.04852674e-06 8.94048980e-06]]

 [[4.62421827e-07 3.47249123e-06]
  [4.66305199e-07 3.46954385e-06]]

 [[4.34126118e-07 2.87535595e-06]
  [4.43684684e-07 2.87178748e-06]]]
[0.00234316 0.00103805 0.0008312 ]


Opti method 2

In [14]:
# nb_basis_list = np.array([10, 20 ,30])
# regularization_parameter_list = np.array([0.01, 0.0001, 0.000001])
# h_param_list = np.array([0.01, 0.1, 0.2])
nb_basis_list = np.array([20, 25])
regularization_parameter_list = np.array([1e-06, 5e-06])
h_param_list = np.array([0.01, 0.015, 0.02])
h_opt, nb_basis_opt, regularization_parameter_opt, tab_errors = LocalApproxFrenetODE(grid, Z=Z).grid_search_optimization_hyperparameters(h_param_list, nb_basis_list, regularization_parameter_list, method='2', n_splits=20)

Begin grid search optimisation with 12 combinations of parameters...
nb_basis: 20 h: 0.01 lbda: 1e-06
nb_basis: 20 h: 0.01 lbda: 5e-06
nb_basis: 20 h: 0.015 lbda: 1e-06
nb_basis: 20 h: 0.015 lbda: 5e-06
nb_basis: 20 h: 0.02 lbda: 1e-06
nb_basis: 20 h: 0.02 lbda: 5e-06
nb_basis: 25 h: 0.01 lbda: 1e-06
nb_basis: 25 h: 0.01 lbda: 5e-06
nb_basis: 25 h: 0.015 lbda: 1e-06
nb_basis: 25 h: 0.015 lbda: 5e-06
nb_basis: 25 h: 0.02 lbda: 1e-06
nb_basis: 25 h: 0.02 lbda: 5e-06
Optimal parameters selected by grid search optimisation:  bandwidth = 0.02 nb_basis = 20 regularization_parameter = 1e-06


In [15]:
print(tab_errors)

[[[0.0027047  0.01144973]
  [0.00123287 0.00465421]
  [0.00091312 0.00294789]]

 [[0.00269955 0.01141146]
  [0.00118651 0.00472099]
  [0.00091701 0.00301776]]]
